/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviousGamesRouteImport } from './routes/previous-games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrucoMatchIdRouteImport } from './routes/truco/$matchId'
import { Route as LivreMatchIdRouteImport } from './routes/livre/$matchId'

const PreviousGamesRoute = PreviousGamesRouteImport.update({
  id: '/previous-games',
  path: '/previous-games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoMatchIdRoute = TrucoMatchIdRouteImport.update({
  id: '/truco/$matchId',
  path: '/truco/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreMatchIdRoute = LivreMatchIdRouteImport.update({
  id: '/livre/$matchId',
  path: '/livre/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/livre/$matchId': typeof LivreMatchIdRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/livre/$matchId': typeof LivreMatchIdRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/livre/$matchId': typeof LivreMatchIdRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/previous-games' | '/livre/$matchId' | '/truco/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/previous-games' | '/livre/$matchId' | '/truco/$matchId'
  id:
    | '__root__'
    | '/'
    | '/previous-games'
    | '/livre/$matchId'
    | '/truco/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviousGamesRoute: typeof PreviousGamesRoute
  LivreMatchIdRoute: typeof LivreMatchIdRoute
  TrucoMatchIdRoute: typeof TrucoMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/previous-games': {
      id: '/previous-games'
      path: '/previous-games'
      fullPath: '/previous-games'
      preLoaderRoute: typeof PreviousGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco/$matchId': {
      id: '/truco/$matchId'
      path: '/truco/$matchId'
      fullPath: '/truco/$matchId'
      preLoaderRoute: typeof TrucoMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre/$matchId': {
      id: '/livre/$matchId'
      path: '/livre/$matchId'
      fullPath: '/livre/$matchId'
      preLoaderRoute: typeof LivreMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviousGamesRoute: PreviousGamesRoute,
  LivreMatchIdRoute: LivreMatchIdRoute,
  TrucoMatchIdRoute: TrucoMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
