/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviousGamesRouteImport } from './routes/previous-games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrucoSetupRouteImport } from './routes/truco/setup'
import { Route as TrucoMatchIdRouteImport } from './routes/truco/$matchId'

const PreviousGamesRoute = PreviousGamesRouteImport.update({
  id: '/previous-games',
  path: '/previous-games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoSetupRoute = TrucoSetupRouteImport.update({
  id: '/truco/setup',
  path: '/truco/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucoMatchIdRoute = TrucoMatchIdRouteImport.update({
  id: '/truco/$matchId',
  path: '/truco/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
  '/truco/setup': typeof TrucoSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
  '/truco/setup': typeof TrucoSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previous-games': typeof PreviousGamesRoute
  '/truco/$matchId': typeof TrucoMatchIdRoute
  '/truco/setup': typeof TrucoSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/previous-games' | '/truco/$matchId' | '/truco/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/previous-games' | '/truco/$matchId' | '/truco/setup'
  id: '__root__' | '/' | '/previous-games' | '/truco/$matchId' | '/truco/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviousGamesRoute: typeof PreviousGamesRoute
  TrucoMatchIdRoute: typeof TrucoMatchIdRoute
  TrucoSetupRoute: typeof TrucoSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/previous-games': {
      id: '/previous-games'
      path: '/previous-games'
      fullPath: '/previous-games'
      preLoaderRoute: typeof PreviousGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco/setup': {
      id: '/truco/setup'
      path: '/truco/setup'
      fullPath: '/truco/setup'
      preLoaderRoute: typeof TrucoSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truco/$matchId': {
      id: '/truco/$matchId'
      path: '/truco/$matchId'
      fullPath: '/truco/$matchId'
      preLoaderRoute: typeof TrucoMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviousGamesRoute: PreviousGamesRoute,
  TrucoMatchIdRoute: TrucoMatchIdRoute,
  TrucoSetupRoute: TrucoSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
